/*
  # SocialFlow AI - Initial Database Schema

  ## Overview
  Creates the foundational database structure for the SocialFlow AI platform,
  including user profiles, social media accounts, content management, and subscriptions.

  ## New Tables

  ### 1. profiles
  - `id` (uuid, primary key) - Links to Clerk user ID
  - `email` (text, unique, not null) - User's email address
  - `full_name` (text) - User's display name
  - `avatar_url` (text) - Profile picture URL
  - `timezone` (text, default 'UTC') - User's timezone for scheduling
  - `created_at` (timestamptz) - Account creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 2. connected_accounts
  - `id` (uuid, primary key) - Unique account identifier
  - `user_id` (uuid, foreign key) - References profiles.id
  - `platform` (text, not null) - Social platform name (facebook, instagram, x, linkedin, tiktok)
  - `platform_user_id` (text, not null) - Platform-specific user/page ID
  - `platform_username` (text) - Username/handle on the platform
  - `access_token` (text) - Encrypted access token
  - `refresh_token` (text) - Encrypted refresh token
  - `token_expires_at` (timestamptz) - Token expiration time
  - `status` (text, default 'active') - Connection status (active, expired, disconnected)
  - `connected_at` (timestamptz) - Initial connection timestamp
  - `last_used_at` (timestamptz) - Last successful post timestamp
  - `created_at` (timestamptz) - Record creation timestamp

  ### 3. content_drafts
  - `id` (uuid, primary key) - Unique draft identifier
  - `user_id` (uuid, foreign key) - References profiles.id
  - `title` (text) - Draft title/description
  - `content` (text, not null) - Post content/caption
  - `media_urls` (jsonb, default '[]') - Array of media URLs
  - `hashtags` (text[]) - Array of hashtags
  - `platforms` (text[], default '{}') - Target platforms
  - `ai_generated` (boolean, default false) - Whether generated by AI
  - `generation_prompt` (text) - Original AI prompt used
  - `created_at` (timestamptz) - Draft creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 4. scheduled_posts
  - `id` (uuid, primary key) - Unique post identifier
  - `user_id` (uuid, foreign key) - References profiles.id
  - `draft_id` (uuid, foreign key, nullable) - References content_drafts.id
  - `content` (text, not null) - Post content
  - `media_urls` (jsonb, default '[]') - Array of media URLs
  - `platforms` (jsonb, not null) - Platform-specific post data
  - `scheduled_for` (timestamptz, not null) - Scheduled publish time
  - `status` (text, default 'pending') - Status (pending, published, failed, cancelled)
  - `published_at` (timestamptz) - Actual publish timestamp
  - `error_message` (text) - Error details if failed
  - `external_post_ids` (jsonb, default '{}') - Platform-specific post IDs
  - `created_at` (timestamptz) - Record creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 5. workflows
  - `id` (uuid, primary key) - Unique workflow identifier
  - `user_id` (uuid, foreign key) - References profiles.id
  - `name` (text, not null) - Workflow name
  - `description` (text) - Workflow description
  - `trigger_type` (text, not null) - Trigger type (schedule, webhook, manual)
  - `trigger_config` (jsonb, not null) - Trigger configuration
  - `actions` (jsonb, not null) - Array of workflow actions
  - `is_active` (boolean, default false) - Whether workflow is enabled
  - `n8n_workflow_id` (text) - External n8n workflow ID
  - `last_run_at` (timestamptz) - Last execution timestamp
  - `next_run_at` (timestamptz) - Next scheduled run
  - `created_at` (timestamptz) - Workflow creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ### 6. workflow_executions
  - `id` (uuid, primary key) - Unique execution identifier
  - `workflow_id` (uuid, foreign key) - References workflows.id
  - `user_id` (uuid, foreign key) - References profiles.id
  - `status` (text, not null) - Execution status (running, success, failed)
  - `started_at` (timestamptz, not null) - Execution start time
  - `completed_at` (timestamptz) - Execution completion time
  - `error_message` (text) - Error details if failed
  - `execution_data` (jsonb) - Execution context and results
  - `created_at` (timestamptz) - Record creation timestamp

  ### 7. subscriptions
  - `id` (uuid, primary key) - Unique subscription identifier
  - `user_id` (uuid, foreign key) - References profiles.id
  - `stripe_customer_id` (text, unique) - Stripe customer ID
  - `stripe_subscription_id` (text, unique) - Stripe subscription ID
  - `plan_name` (text, not null) - Plan name (free, pro, business)
  - `status` (text, not null) - Subscription status (active, cancelled, past_due)
  - `current_period_start` (timestamptz) - Billing period start
  - `current_period_end` (timestamptz) - Billing period end
  - `cancel_at_period_end` (boolean, default false) - Whether cancellation is scheduled
  - `created_at` (timestamptz) - Subscription creation timestamp
  - `updated_at` (timestamptz) - Last update timestamp

  ## Security
  - Enable Row Level Security on all tables
  - Add policies for authenticated users to access only their own data
  - Implement secure token storage with encryption

  ## Indexes
  - Create indexes on frequently queried columns for performance optimization
*/

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  full_name text,
  avatar_url text,
  timezone text DEFAULT 'UTC',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create connected_accounts table
CREATE TABLE IF NOT EXISTS connected_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  platform text NOT NULL,
  platform_user_id text NOT NULL,
  platform_username text,
  access_token text,
  refresh_token text,
  token_expires_at timestamptz,
  status text DEFAULT 'active',
  connected_at timestamptz DEFAULT now(),
  last_used_at timestamptz,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, platform, platform_user_id)
);

-- Create content_drafts table
CREATE TABLE IF NOT EXISTS content_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title text,
  content text NOT NULL,
  media_urls jsonb DEFAULT '[]'::jsonb,
  hashtags text[],
  platforms text[] DEFAULT '{}',
  ai_generated boolean DEFAULT false,
  generation_prompt text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create scheduled_posts table
CREATE TABLE IF NOT EXISTS scheduled_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  draft_id uuid REFERENCES content_drafts(id) ON DELETE SET NULL,
  content text NOT NULL,
  media_urls jsonb DEFAULT '[]'::jsonb,
  platforms jsonb NOT NULL,
  scheduled_for timestamptz NOT NULL,
  status text DEFAULT 'pending',
  published_at timestamptz,
  error_message text,
  external_post_ids jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create workflows table
CREATE TABLE IF NOT EXISTS workflows (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  trigger_type text NOT NULL,
  trigger_config jsonb NOT NULL,
  actions jsonb NOT NULL,
  is_active boolean DEFAULT false,
  n8n_workflow_id text,
  last_run_at timestamptz,
  next_run_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create workflow_executions table
CREATE TABLE IF NOT EXISTS workflow_executions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workflow_id uuid NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  status text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  error_message text,
  execution_data jsonb,
  created_at timestamptz DEFAULT now()
);

-- Create subscriptions table
CREATE TABLE IF NOT EXISTS subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  stripe_customer_id text UNIQUE,
  stripe_subscription_id text UNIQUE,
  plan_name text NOT NULL DEFAULT 'free',
  status text NOT NULL DEFAULT 'active',
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_connected_accounts_user_id ON connected_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_connected_accounts_status ON connected_accounts(status);
CREATE INDEX IF NOT EXISTS idx_content_drafts_user_id ON content_drafts(user_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_user_id ON scheduled_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_scheduled_for ON scheduled_posts(scheduled_for);
CREATE INDEX IF NOT EXISTS idx_scheduled_posts_status ON scheduled_posts(status);
CREATE INDEX IF NOT EXISTS idx_workflows_user_id ON workflows(user_id);
CREATE INDEX IF NOT EXISTS idx_workflows_is_active ON workflows(is_active);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_workflow_id ON workflow_executions(workflow_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);

-- Enable Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE connected_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies for profiles
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  TO authenticated
  USING (id = auth.uid());

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  TO authenticated
  WITH CHECK (id = auth.uid());

-- Create RLS Policies for connected_accounts
CREATE POLICY "Users can view own connected accounts"
  ON connected_accounts FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own connected accounts"
  ON connected_accounts FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own connected accounts"
  ON connected_accounts FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own connected accounts"
  ON connected_accounts FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- Create RLS Policies for content_drafts
CREATE POLICY "Users can view own drafts"
  ON content_drafts FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own drafts"
  ON content_drafts FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own drafts"
  ON content_drafts FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own drafts"
  ON content_drafts FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- Create RLS Policies for scheduled_posts
CREATE POLICY "Users can view own scheduled posts"
  ON scheduled_posts FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own scheduled posts"
  ON scheduled_posts FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own scheduled posts"
  ON scheduled_posts FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own scheduled posts"
  ON scheduled_posts FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- Create RLS Policies for workflows
CREATE POLICY "Users can view own workflows"
  ON workflows FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own workflows"
  ON workflows FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own workflows"
  ON workflows FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can delete own workflows"
  ON workflows FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- Create RLS Policies for workflow_executions
CREATE POLICY "Users can view own workflow executions"
  ON workflow_executions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own workflow executions"
  ON workflow_executions FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- Create RLS Policies for subscriptions
CREATE POLICY "Users can view own subscription"
  ON subscriptions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Users can insert own subscription"
  ON subscriptions FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own subscription"
  ON subscriptions FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_content_drafts_updated_at
  BEFORE UPDATE ON content_drafts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_scheduled_posts_updated_at
  BEFORE UPDATE ON scheduled_posts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_workflows_updated_at
  BEFORE UPDATE ON workflows
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_subscriptions_updated_at
  BEFORE UPDATE ON subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
